site_name: Autonomous Mower Project

docs_dir: docs

nav:
  - Index: Home.md
  - Project:  
      - Overview: Project/Overview/Overview.md  
      - Architecture: 
          - Hardware: Project/Architecture/Hardware.md
          - Software: Project/Architecture/Software.md
      - Design: 
          - Something: Project/Design/Something.md
  - Author: Author.md
  - Other informations:
      - Rules during implementation: Info/Rules.md
      - Installation: Info/Installation.md

theme:
  name: material
