site_name: Autonomous Mower Project

docs_dir: docs

nav:
  - Home: Home.md
  - Project:  
      - Overview: Project/Overview.md  
      - Architecture: 
          - Hardware: Project/Architecture/Hardware.md
          - Software: Project/Architecture/Software.md
      - Design:
          - Conceptual choices: Project/Design/Conceptual_choices.md
          - Implementation: Project/Design/Implementation.md
      - Testing: Project/Testing.md
      - Future work: Project/Future_work.md
      - Other informations:
          - Rules during implementation: Project/Info/Rules.md
          - Installation: Project/Info/Installation.md
  - Author: Author.md

theme:
  name: material
